### PR TITLE
Update deps - v6.0.0 formatjs

### PR DESCRIPTION
**Pull request by snewcomer**
screen shot 2018-11-05 at 07 46 57

### CODE REVIEW

**Comment by jasonmit** [comment]
@snewcomer I would merge then cut 2.0

**Comment by jasonmit** [comment]
@snewcomer feel free to version when you're ready :)

**Comment by snewcomer** [comment]
👍 

https://www.npmjs.com/package/broccoli-cldr-data

Looks like I might not be a collaborator so I can wait for you to publish or would be happy to be added as well!

**Comment by snewcomer** [comment]
Also fyi tagged 2.0 - https://github.com/ember-intl/broccoli-cldr-data/releases

**Comment by jasonmit** [comment]
@snewcomer ah!  We can publish 2.0 under the @ember-intl org.  You should have access to do that!

**Comment by snewcomer** [comment]
@jasonmit This is what I am seeing up on npm. 

Not in use (v2.0 1 year ago): https://www.npmjs.com/package/@ember-intl/broccoli-cldr-data
In use (v1.1.2 5 months ago): https://www.npmjs.com/package/broccoli-cldr-data

**Comment by jasonmit** [comment]
3.0? :)

I wish I had an explanation but I don't, I probably mistakenly published 2.0 under that namespace.

**Pull request merged**
